name: NPM Asurgent ESLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/eslint-config-asurgent
          scope: 'asurgent'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
